const navbar = document.querySelector('.navbar-brand').addEventListener('click', function() {
    const alertBox = document.createElement('div');
    alertBox.style.display = 'flex';
    alertBox.style.justifyContent = 'center';
    alertBox.style.alignItems = 'center';
    alertBox.style.backgroundColor = 'pink';
    alertBox.style.color = 'red';
    alertBox.style.fontSize = '24px';
    alertBox.style.fontWeight = 'bold';
    alertBox.style.width = '50%';
    alertBox.style.height = '90%';
    alertBox.style.position = 'fixed';
    alertBox.style.paddingLeft = '40px';
    alertBox.style.top = '0';
    alertBox.style.left = '90%';
    alertBox.style.marginTop = '2%';
    alertBox.style.zIndex = '9999';
    alertBox.style.transition = 'all 0.5s ease';
    alertBox.style.transform = 'translateX(-100%)';
    alertBox.style.border = '2px solid red';
    alertBox.style.borderRadius = '10px';
    alertBox.style.boxShadow = '0 0 10px 5px rgba(0, 0, 0, 0.5)';
    alertBox.innerText = 'Im Amar Kumar, a frontend web developer from Bihar. I focus on creating user-friendly experiences with HTML, CSS, and JavaScript. My design skills include Canva, and I have 1.5 years of WordPress website development experience.';
    const cancelButton = document.createElement('button');
    cancelButton.innerText = 'ok';
    cancelButton.style.padding = '10px 20px';
    cancelButton.style.backgroundColor = 'red';
    cancelButton.style.color = 'white';
    cancelButton.style.border = 'none';
    cancelButton.style.borderRadius = '5px';
    cancelButton.style.cursor = 'pointer';
    cancelButton.style.marginRight = '100px';
    cancelButton.style.marginTop = '350px';
    cancelButton.style.transition = 'all 0.5s ease';
    cancelButton.addEventListener('click', function() {
        document.body.removeChild(alertBox);
    });
    alertBox.appendChild(cancelButton);
    document.body.appendChild(alertBox);
});